### ISSUE TITLE
No show in hello.xr

### ISSUE THREAD

**Issue by TomGitHub9** [mbucchia/OpenXR-Window-Manager#2]
Hello,
Obviously I make a mistake somewhere, as I know you have great coding capabilities creating the Toolbox!

I build this application using the latest StereoKit version, and it compiles just fine. I make a published version in order to get the .net incorporated with the app. I would love to know how I can get a simple overlay form in OpenXR, and looked at this example.
The problem is:
1) Build/publish-> fine
2) Start "hello.xr' -> fine, I see the boxes in 3D
3) Start Windows-Manager-> do not see anything happening, and get error message that the MR set is now available, or I do not see anything at all happening. 
Is there a specific "hello.xr"  that I need to use?
As far as I am aware both use the XR_EXTX_overlay.dll that I made impicit in register.

Thanks!

**Comment by mbucchia** [comment]
This project is dead, `XR_EXTX_overlay` is way to buggy to be usable, and is not worth pursuing.

I will mark this project as ARCHIVE so there is no confusion.

**Comment by TomGitHub9** [comment]
Thanks for your reply Matthieu.It is understood that the project is dead and archived.I did make a build also with reference to your own XR_API_Layer_Novendor_toolkit.dll (this overlay api is active in implicit register due to the toolkit).I was hoping that this would give me an overlay, over MSFS or hello.xr.Reason is that Stereokit is easy and works nicely with C#, so would be nice for overlays.So far no luck for me.Are you aware of an easy way/fix/example?Thank you for your time, i appreciate it!
-------- Oorspronkelijk bericht --------Van: Matthieu Bucchianeri ***@***.***> Datum: 11-01-2023  18:25  (GMT+01:00) Aan: mbucchia/OpenXR-Window-Manager ***@***.***> Cc: TomGitHub9 ***@***.***>, Author ***@***.***> Onderwerp: Re: [mbucchia/OpenXR-Window-Manager] No show in hello.xr (Issue #2) 
Closed #2 as completed.

**Comment by mbucchia** [comment]
> Reason is that Stereokit is easy and works nicely with C#, so would be nice for overlays.

This was my thinking too when I experimented with this, however the outcome of my research is:

1) XR_EXT_overlay as a standard it over complicated. It is meant for true multi-application (so even 3D content) with shared input and bridging of advanced extensions such as anchors or environment understanding. For 2D overlays, this is way to complicated.
2) Due to 1), the implementation of it as an API layer is out of reach: LunarG worked on their API layer but they haven't pursued in 2 years. Upon picking up their code, I dealt with many complex bugs, and finally got it to work-ish....
3) ...but it did not work well. It only worked with WMR really, and never got the API layer to work with other runtimes. The code is insanely complicated due to 1), and IMO not worth pursuing.

IMO the path forward today to bring 2D overlays (which is 99% of what people want) is to design a product specific for 2D overlays. One issue is that defining a new OpenXR extension is a complex process, and if not done well, will introduce significant issues on the long term.

My proposal is instead to reuse the well-known IVROverlay (which has bindings in C# too), and plug that into an OpenXR API layer. This will avoid potential fragmentation that a "bad" OpenXR extension design would create, and also make it easier to port existing 2D overlays. This proposal is outline here: https://github.com/mbucchia/OverXR/wiki. Unfortunately, I do not have time and resources right now for implementation.

You are aware of my other projects like OpenXR Toolkit and the API layer template, and I will be spending time there. I am currently working on improvements to the API layer template to include support for drawing inside the layer, which would be a building block of either 1) custom API layers for overlays or 2) pursuing the "OverXR" proposal above. But these are still weeks, if not months out.

**Comment by TomGitHub9** [comment]
Hi Matthieu,

 

Thanks a lot for your reply and spending time to answer.

 

It would be great to be able to have a template that can be used easy to include 2D Winforms/UWP forms as overlay in WMR (MSFS). I hope that your effort with the API layer template will indeed make this possible.

Although I was able to build the API layer template, I was not able yet to include 2D content visible inside the layer.

As your Toolkit includes a 2D layer, I hoped to be able to pick upon the structure.

 

I am also aware of your OpenComposite efforts. This looks very promising, and I already tried to use  OpenVR overlays as an input for the OpenComposite tool.  

OpenVR overlays are less complicated (using OVRSharp) and this would be a nice workaround to include 2D overlays in OpenXR. 

At the moment OpenComposite is not supporting these 2D Overlays yet. 

 

I am using MSFS in VR since the first Oculus DK1, and appreciate all your efforts for the community.

OpenXR Toolkit is great! 

 

 

 

Van: Matthieu Bucchianeri ***@***.***> 
Verzonden: woensdag 11 januari 2023 21:44
Aan: mbucchia/_ARCHIVE_OpenXR-Window-Manager ***@***.***>
CC: TomGitHub9 ***@***.***>; Author ***@***.***>
Onderwerp: Re: [mbucchia/_ARCHIVE_OpenXR-Window-Manager] No show in hello.xr (Issue #2)

 

Reason is that Stereokit is easy and works nicely with C#, so would be nice for overlays.

This was my thinking too when I experimented with this, however the outcome of my research is:

1.	XR_EXT_overlay as a standard it over complicated. It is meant for true multi-application (so even 3D content) with shared input and bridging of advanced extensions such as anchors or environment understanding. For 2D overlays, this is way to complicated.
2.	Due to 1), the implementation of it as an API layer is out of reach: LunarG worked on their API layer but they haven't pursued in 2 years. Upon picking up their code, I dealt with many complex bugs, and finally got it to work-ish....
3.	...but it did not work well. It only worked with WMR really, and never got the API layer to work with other runtimes. The code is insanely complicated due to 1), and IMO not worth pursuing.

IMO the path forward today to bring 2D overlays (which is 99% of what people want) is to design a product specific for 2D overlays. One issue is that defining a new OpenXR extension is a complex process, and if not done well, will introduce significant issues on the long term.

My proposal is instead to reuse the well-known IVROverlay (which has bindings in C# too), and plug that into an OpenXR API layer. This will avoid potential fragmentation that a "bad" OpenXR extension design would create, and also make it easier to port existing 2D overlays. This proposal is outline here: https://github.com/mbucchia/OverXR/wiki. Unfortunately, I do not have time and resources right now for implementation.

You are aware of my other projects like OpenXR Toolkit and the API layer template, and I will be spending time there. I am currently working on improvements to the API layer template to include support for drawing inside the layer, which would be a building block of either 1) custom API layers for overlays or 2) pursuing the "OverXR" proposal above. But these are still weeks, if not months out.

**Comment by TomGitHub9** [comment]
Hi Matthieu,

 

So time ago, we got in contact about XR_EXTX_Overlay and the fact that it didn’t work properly as provided on github by LunarG.

Also I couldn’t get the Windows Manager to work.

Since then, I have been able to get it to all work, and also made it work with StereoKit. I can make my own StereoKit apps that are shown as overlay. 

 

 

So far so good, though for some reason I cannot get the overlay running with MSFS2020.

If the XR_EXTX_overlay is active as trampoline API, MSFS2020 will just freeze when go to Mixed Reality Mode in the game.

This surprised me as the overlay should be according to OpenXR spec, and I suppose that MSFS2020 will work with that spec also.

 

My quick question is:

1.	Are you aware of a specific requirement and or bug that is the reason for MSFS2020 not working with the XR_EXTX_overlay

I know it is a very complex overlay but therefore would have expected to work according to OpenXR spec with MSFS2020

2.	I noticed that you took a far more advanced route in the OpenXR-Toolkit, and am aware of the IVROverlay proposal. 

In the OpenXR-Toolkit, I couldn’t find any intercept xrEndFrame() however. 

May I ask what trampoline jump hook you took?

 

Thank you so much for a reply

 

 

Best regards!

**Comment by TomGitHub9** [comment]
Hi Matthieu,I only got in working on WMR as well. But it works fine there, but not on MSFS.Good to hear you have a framework coming out soon. Happy to test it if you have something to share, though I am way below you programming skills.Thanks for your prompt reply!
-------- Oorspronkelijk bericht --------Van: Matthieu Bucchianeri ***@***.***> Datum: 07-03-2023  17:29  (GMT+01:00) Aan: mbucchia/_ARCHIVE_OpenXR-Window-Manager ***@***.***> Cc: TomGitHub9 ***@***.***>, Author ***@***.***> Onderwerp: Re: [mbucchia/_ARCHIVE_OpenXR-Window-Manager] No show in hello.xr (Issue #2) 
I couldn't get MSFS2020 to work either. I think it's because it does frame pipelining (it has up to 2 frames in-flight).
Also, when you say you got it to work, did you test it with all OpenXR runtimes? I couldn't get display on Quest, Varjo, the perf was not good on SteamVR... it only worked OK on WMR.
Way too complicated :)
I have been working on providing what OpenXR Toolkit does as a standalone framework, and I'm very close to having something to share. I need to to a little bit of documentation before I push it publicly. I haven't worked on the inputs side yet though, but the display side is all ready.
I think that would be a much better way to make overlays.

**Comment by mbucchia** [comment]
Goal is to make it easy for developers. I am working on a mode where you can import a desktop window such as a Winform.

I'll share with you the details as soon as ready, perhaps before next week.

**Comment by TomGitHub9** [comment]
That sounds great!Coming back to the solution to have a separate app, like made with stereo kit, though native without the .net addons to work with msfs, would be nice.Such app then needs to relate to the API overlay and get its graphics to the chain via the API. I have looked at your toolkit and it seems the the API itself is adding the layergraphics. So not an external layer that relates to the API, but the API itself is also the layer. I might be very wrong, but it was hard to see at what point the API is called to include graphics. Same for the template layer framework; how does the API work with the layer to be included. So it would really help if you could refer to that in the documentation for the framework. And maybe Stereo kit might be including the reference to overlays is their c++ native solution.Best regardsVan: Matthieu Bucchianeri ***@***.***>Verstuurd: dinsdag 7 maart 2023 21:13Aan: mbucchia/_ARCHIVE_OpenXR-Window-Manager ***@***.***>CC: TomGitHub9 ***@***.***>; Author ***@***.***>Onderwerp: Re: [mbucchia/_ARCHIVE_OpenXR-Window-Manager] No show in hello.xr (Issue #2)
Goal is to make it easy for developers. I am working on a mode where you can import a desktop window such as a Winform.
I'll share with you the details as soon as ready, perhaps before next week.

**Comment by mbucchia** [comment]
I have an example of how to import a Winform running in a separate process. This will be one of the things shown in my tutorial once I publish it.

The main challenge is inputs, especially mouse input. I haven't really solved that yet.

**Comment by mbucchia** [comment]
Here is an example of a Winform imported into a game (iRacing) in this case. However, there is no interaction at this time (unless you go to the desktop and interact with the Winform directly).

![image](https://user-images.githubusercontent.com/69611560/224581415-cfcd1e46-b1cf-432d-9fdf-667ddf3afa1e.png)

**Comment by mbucchia** [comment]
@TomGitHub9 I have released a first version of the utilities library for my API layer template. I'm also working on 4 tutorials to show how to get things done. Tutorial 4 corresponds to the importing of a 2D window into VR, which could be of interest to you. The tutorial isn't published yet, but the source code is  accessible in the example branch.

https://github.com/mbucchia/OpenXR-Layer-Template/wiki

**Comment by TomGitHub9** [comment]
Hi Matthieu,Thanks for letting me know!I will have a look.Rgds!
-------- Oorspronkelijk bericht --------Van: Matthieu Bucchianeri ***@***.***> Datum: 22-04-2023  10:47  (GMT+01:00) Aan: mbucchia/_ARCHIVE_OpenXR-Window-Manager ***@***.***> Cc: TomGitHub9 ***@***.***>, Mention ***@***.***> Onderwerp: Re: [mbucchia/_ARCHIVE_OpenXR-Window-Manager] No show in hello.xr (Issue #2) 
@TomGitHub9 I have released a first version of the utilities library for my API layer template. I'm also working on 4 tutorials to show how to get things done. Tutorial 4 corresponds to the importing of a 2D window into VR, which could be of interest to you. The tutorial isn't published yet, but the source code is  accessible in the example branch.
https://github.com/mbucchia/OpenXR-Layer-Template/wiki
